### ISSUE TITLE
Help with Copy Files

### ISSUE THREAD

**Issue by fvgtekken** [FrancoisGeyser/cPanel-yml#3]
Hello!  I'm using  manual pull o deploy commit ahead, and I can´t  found the commad for copy all the **_content inside of may build folder_** in the repo to the root of public_html

Here is my code exmaple:
deployment:
  tasks:
    - export DEPLOYPATH=/home/myusername/public_html/
    - /bin/cp  /build/* $DEPLOYPATH

the result is that copy the folder itself no the content 

Thanks for the help!

**Comment by FullMe7alJacke7** [comment]
I think you need to add -r
Like so...

`---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myshotshare/public_html/app/public
    - /bin/cp -r * $DEPLOYPATH`
